### ------------- [          ORDER OF INSERT         ]------------ ###
# 1-0. Product2 [1/3]
# 1-1. PricebookEntry [1/3]

### ----------- [ Products_Standard_npsp.recipe.yml Summary ]---------- ###
# This recipe creates [1] product among three choices: "Individual Membership", "Houshold Membership", "Corporate Membership"
# Creates 1 Pricebook entry to the standard price book
# This recipe queries into a connected cci org to retrieve Standard Pricebook Id

### ----------- [               CLI RUN                ]---------- ###

# cci task run generate_and_load_from_yaml --generator_yaml snowfakery_samples/npsp/Products_Standard_npsp.recipe.yml --org dev
# snowfakery snowfakery_samples/npsp/Products_Standard_npsp.recipe.yml --output-format json --output-file snowfakery_samples/temp/output.json --plugin-option org_name dev

### ----------- [            Recipe Starts             ]---------- ###

- plugin: snowfakery.standard_plugins.Salesforce.SOQLDataset

- object: Product2
  nickname: p1
  fields:
    Name: 
      random_choice:
        - Individual Membership
        - Household Membership
        - Corporate Membership
    ProductCode: 
      if:
        - choice:
            when: ${{Name == 'Individual Membership'}}
            pick: INDVDL-MEMBER-ANNUAL
        - choice: 
            when: ${{Name == 'Household Membership'}}
            pick: HSHLD-MEMBER-ANNUAL
        - choice: 
            when: ${{Name == 'Corporate Membership'}}
            pick: CRPRT-MEMBER-ANNUAL
        
    Description: 
      fake.text:
        max_nb_chars: 50
    StockKeepingUnit: #sku
    Family: Annual Membership

- object: PricebookEntry
  fields:
    IsActive: true
    UnitPrice: 250
    Product2Id: 
      reference: p1
    __pricebook_from_salesforce:
      SOQLDataset.shuffle:
        fields: Id 
        from: Pricebook2
    Pricebook2Id: ${{__pricebook_from_salesforce.Id}}
        